In [1]:
from glotaran_core import create_parameter_list, Parameter, KineticModel, KMatrix, KineticMegacomplex
from scipy.sparse import dok_matrix
import numpy as np

In [2]:
model = KineticModel()

plist = create_parameter_list([1, ["k1",3]])
model.add_parameter(plist)
model.add_parameter(Parameter(4, label="k2"))
model.add_parameter(Parameter(5.87, label="k3"))

m = dok_matrix((3, 3), dtype=np.int32)
m[0, 0] = 2
m[1, 1] = 3
m[2, 2] = 4
km1 = KMatrix("km1", m)
model.add_k_matrix(km1)
cmplx1 = KineticMegacomplex("cmplx1", "km1")

print(model)
    

Parameter
---------

Index: 1 Initial Value: 1.0 Label: None
Index: 2 Initial Value: 3.0 Label: k1
Index: 3 Initial Value: 4.0 Label: k2
Index: 4 Initial Value: 5.87 Label: k3


K-Matrices
----------

Label: km1
Matrix:
[[2 0 0]
 [0 3 0]
 [0 0 4]]


